GET http://localhost:3001/api/currency/

###

GET http://localhost:3001/api/currency/2

###

POST http://localhost:3001/api/currency/
Content-Type: application/json

{
    "currencyCode": "SAR",
    "country": "SAUDI ARABIA",
    "conversionRate": 2.78
}

###

PUT http://localhost:3001/api/currency/2
Content-Type: application/json

{
    "conversionRate": 0.5
}

###

DELETE http://localhost:3001/api/currency/2